name: Cache Demo Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-f7b980d
        with:
          path: ~/.npm
          key: cache-f7b980d
          restore-keys: |
            cache-f7b980d
            
      - name: prime-cache-f7b980d
        run: |
          if [ "${{ steps.cache-f7b980d.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit ✅"
          else
            echo "Cache miss ❌"
          fi
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present
