name: Hello World Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 24f2008454@ds.study.iitm.ac.in
        run: echo "Hello, World!"
      
      - name: Current date
        run: date
